#!/usr/bin/env python3
"""Render deterministic Markdown projections from the normalized knowledge graph.

The concept files remain the source of truth.  This renderer consumes only the
validated model exposed by ``scripts/build-knowledge-map.py`` and writes
navigation pages beneath ``maps/``.
"""

from __future__ import annotations

import argparse
import importlib.util
import os
import re
import sys
from pathlib import Path
from typing import Any, Iterable


RELATIONSHIP_LABELS = {
    "prerequisites": "prerequisite",
    "enables": "enables",
    "contrasts_with": "contrasts with",
    "related": "related to",
}
STATUS_LABELS = {
    "not-started": "not started",
    "developing": "developing",
    "mastered": "mastered",
}
SAFE_MERMAID_ID = re.compile(r"[^a-zA-Z0-9_]")


def parse_arguments(arguments: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        type=Path,
        default=Path.cwd(),
        help="Learning Lab repository root (default: current directory)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="generated map directory (default: <root>/maps)",
    )
    return parser.parse_args(arguments)


def load_graph_builder() -> Any:
    """Import the single normalized-model producer without reparsing sources."""

    path = Path(__file__).with_name("build-knowledge-map.py")
    specification = importlib.util.spec_from_file_location("knowledge_map_builder", path)
    if specification is None or specification.loader is None:
        raise RuntimeError(f"cannot import knowledge-map builder: {path}")
    module = importlib.util.module_from_spec(specification)
    sys.modules[specification.name] = module
    specification.loader.exec_module(module)
    return module


def relative_link(source: Path, target: Path, label: str) -> str:
    """Make an ordinary portable Markdown link between generated/source files."""

    path = Path(os.path.relpath(target, start=source.parent)).as_posix()
    return f"[{label}]({path})"


def source_link(page: Path, root: Path, repository_path: str, label: str) -> str:
    return relative_link(page, root / repository_path, label)


def generated_warning() -> list[str]:
    return [
        "> [!WARNING]",
        "> Generated from the validated normalized knowledge graph. Do not edit this file directly.",
        "> Regenerate with `python3 scripts/render-knowledge-map-markdown.py`.",
        "",
    ]


def title_case(identifier: str) -> str:
    words = identifier.split("-")
    return " ".join("AI" if word == "ai" else word.title() for word in words)


def mermaid_id(identifier: str) -> str:
    return SAFE_MERMAID_ID.sub("_", identifier)


def mermaid_node(node: dict[str, Any]) -> str:
    return f'  {mermaid_id(node["id"])}["{node["title"].replace(chr(34), chr(39))}"]'


def typed_mermaid(nodes: Iterable[dict[str, Any]], edges: Iterable[dict[str, str]]) -> list[str]:
    selected_nodes = {node["id"]: node for node in nodes}
    selected_edges = [
        edge
        for edge in edges
        if edge["source"] in selected_nodes and edge["target"] in selected_nodes
    ]
    if not selected_nodes:
        return ["No concepts are available for this view.", ""]

    lines = ["```mermaid", "flowchart LR"]
    lines.extend(mermaid_node(selected_nodes[identifier]) for identifier in sorted(selected_nodes))
    for edge in sorted(selected_edges, key=lambda value: (value["source"], value["type"], value["target"])):
        connector = "---" if edge["type"] in {"contrasts_with", "related"} else "-->"
        lines.append(
            f'  {mermaid_id(edge["source"])} {connector}|{RELATIONSHIP_LABELS[edge["type"]]}| '
            f'{mermaid_id(edge["target"])}'
        )
    lines.extend(["```", ""])
    return lines


def relationship_legend() -> list[str]:
    return [
        "## Legend",
        "",
        "- `prerequisite`: must be understood before the source concept.",
        "- `enables`: capability the source concept makes materially easier or possible.",
        "- `contrasts with`: deliberate distinction from an easily confused concept.",
        "- `related to`: useful non-dependency association.",
        "- Mastery status is derived from linked learning records: `not started`, `developing`, or `mastered`.",
        "",
    ]


def node_table(page: Path, root: Path, nodes: Iterable[dict[str, Any]]) -> list[str]:
    rows = sorted(nodes, key=lambda node: node["id"])
    if not rows:
        return ["No concepts match this view.", ""]
    lines = ["| Concept | Kind | Mastery | Summary |", "| --- | --- | --- | --- |"]
    for node in rows:
        link = source_link(page, root, node["path"], node["title"])
        status = STATUS_LABELS[node["mastery"]["status"]]
        lines.append(f"| {link} | {node['kind']} | {status} | {node['summary']} |")
    lines.append("")
    return lines


def relation_list(page: Path, root: Path, node_by_id: dict[str, dict[str, Any]], identifiers: Iterable[str]) -> str:
    entries = [
        source_link(page, root, node_by_id[identifier]["path"], node_by_id[identifier]["title"])
        for identifier in sorted(identifiers)
    ]
    return ", ".join(entries) if entries else "None."


def incoming_relationship_sentence(relationship_type: str) -> str:
    return {
        "prerequisites": "depends on",
        "enables": "enables",
        "contrasts_with": "contrasts with",
        "related": "is related to",
    }[relationship_type]


def write_page(path: Path, lines: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def render_entrypoint(root: Path, output: Path, graph: dict[str, Any]) -> None:
    page = output / "README.md"
    lines = ["# Knowledge Map", ""] + generated_warning()
    lines += [
        "This is a generated navigation layer over the canonical concept files and learning evidence.",
        "",
        "## Views",
        "",
        f"- {relative_link(page, output / 'overview.md', 'Bounded overview')}",
        "- Tracks:",
    ]
    for track in graph["tracks"]:
        lines.append(f"  - {relative_link(page, output / 'tracks' / f'{track}.md', title_case(track))}")
    lines.append("- Case labs:")
    for case_lab in graph["case_labs"]:
        title = case_lab.get("title") or "Untitled case lab"
        lines.append(
            f"  - {relative_link(page, output / 'case-labs' / f'{case_lab["id"]}.md', title)}"
        )
    lines += ["- Focal concepts:"]
    for node in graph["nodes"]:
        lines.append(
            f"  - {relative_link(page, output / 'concepts' / f'{node["id"]}.md', node["title"])}"
        )
    lines += [""] + relationship_legend()
    write_page(page, lines)


def render_overview(root: Path, output: Path, graph: dict[str, Any]) -> None:
    page = output / "overview.md"
    nodes = [node for node in graph["nodes"] if node["kind"] in {"orientation", "foundation"}]
    lines = ["# Bounded Knowledge Overview", ""] + generated_warning()
    lines += [
        "This global spine intentionally includes only orientation and foundation concepts.",
        "Use a track, case-lab, or focal page for a more complete local view.",
        "",
        "## Dependency spine",
        "",
    ]
    lines += typed_mermaid(nodes, graph["edges"])
    lines += ["## Concepts", ""] + node_table(page, root, nodes)
    lines += [f"Back to {relative_link(page, output / 'README.md', 'Knowledge Map') }.", ""]
    write_page(page, lines)


def render_track(page: Path, root: Path, output: Path, graph: dict[str, Any], track: str) -> None:
    node_by_id = {node["id"]: node for node in graph["nodes"]}
    direct = [node for node in graph["nodes"] if track in node["tracks"]]
    direct_ids = {node["id"] for node in direct}
    context_ids = {
        prerequisite
        for node in direct
        for prerequisite in node["relationships"]["prerequisites"]
        if prerequisite not in direct_ids
    }
    context = [node_by_id[identifier] for identifier in sorted(context_ids)]
    lines = [f"# Track: {title_case(track)}", ""] + generated_warning()
    lines += [
        "Direct concepts are explicitly taught or reused by this track. Contextual concepts are one-hop prerequisites only.",
        "",
        "## Direct concepts",
        "",
    ] + node_table(page, root, direct)
    lines += ["## One-hop prerequisite context", ""] + node_table(page, root, context)
    lines += ["## Typed relationships", ""] + typed_mermaid([*direct, *context], graph["edges"])
    lines += [f"Back to {relative_link(page, output / 'README.md', 'Knowledge Map') }.", ""]
    write_page(page, lines)


def render_case_lab(page: Path, root: Path, output: Path, graph: dict[str, Any], case_lab: dict[str, Any]) -> None:
    node_by_id = {node["id"]: node for node in graph["nodes"]}
    direct_ids = tuple(case_lab.get("direct_concepts", ()))
    direct = [node_by_id[identifier] for identifier in direct_ids]
    direct_id_set = set(direct_ids)
    context_ids = {
        prerequisite
        for node in direct
        for prerequisite in node["relationships"]["prerequisites"]
        if prerequisite not in direct_id_set
    }
    context = [node_by_id[identifier] for identifier in sorted(context_ids)]
    title = case_lab.get("title") or "Untitled case lab"
    lines = [f"# Case Lab: {title}", ""] + generated_warning()
    lines += [
        f"Canonical case-lab hub: {source_link(page, root, case_lab['path'], title)}.",
        "",
        "## Strict membership",
        "",
    ] + node_table(page, root, direct)
    if not direct:
        lines += [
            "No concepts have explicit pinned evidence for this case lab yet; the hub alone does not create membership.",
            "",
        ]
    lines += ["## One-hop prerequisite context", ""] + node_table(page, root, context)
    if not context:
        lines += ["No contextual prerequisites are available without direct case-lab membership.", ""]
    lines += ["## Typed relationships", ""] + typed_mermaid([*direct, *context], graph["edges"])
    lines += [f"Back to {relative_link(page, output / 'README.md', 'Knowledge Map') }.", ""]
    write_page(page, lines)


def render_concept(page: Path, root: Path, output: Path, graph: dict[str, Any], node: dict[str, Any]) -> None:
    node_by_id = {candidate["id"]: candidate for candidate in graph["nodes"]}
    outbound_ids = {
        target
        for targets in node["relationships"].values()
        for target in targets
    }
    inbound_edges = [edge for edge in graph["edges"] if edge["target"] == node["id"]]
    neighbouring_ids = outbound_ids | {edge["source"] for edge in inbound_edges}
    neighbours = [node, *(node_by_id[identifier] for identifier in sorted(neighbouring_ids))]
    lines = [f"# Concept: {node['title']}", ""] + generated_warning()
    lines += [node["summary"], "", "## Status", "", f"- Kind: `{node['kind']}`", f"- Mastery: `{STATUS_LABELS[node['mastery']['status']]}`"]
    if node["mastery"]["effective_record"]:
        lines.append(
            "- Effective evidence: "
            + source_link(page, root, node["mastery"]["effective_record"], "learning record")
        )
    else:
        lines.append("- Effective evidence: none linked.")
    lines += ["", "## Direct relationships", ""]
    for relationship_type in RELATIONSHIP_LABELS:
        identifiers = set(node["relationships"][relationship_type])
        if relationship_type in {"contrasts_with", "related"}:
            identifiers.update(
                edge["source"]
                for edge in inbound_edges
                if edge["type"] == relationship_type
            )
        lines.append(
            f"- {RELATIONSHIP_LABELS[relationship_type].capitalize()}: "
            + relation_list(page, root, node_by_id, identifiers)
        )
    lines += ["", "## Incoming relationships", ""]
    directional_inbound = [
        edge for edge in inbound_edges if edge["type"] not in {"contrasts_with", "related"}
    ]
    if directional_inbound:
        for edge in sorted(directional_inbound, key=lambda value: (value["type"], value["source"])):
            source = node_by_id[edge["source"]]
            lines.append(
                f"- {source_link(page, root, source['path'], source['title'])} "
                f"{incoming_relationship_sentence(edge['type'])} this concept."
            )
    else:
        lines.append("No concepts directly point to this concept.")
    lines += ["", "## Tracks", ""]
    if node["tracks"]:
        for track in node["tracks"]:
            lines.append(f"- {relative_link(page, output / 'tracks' / f'{track}.md', title_case(track))}")
    else:
        lines.append("No track memberships.")
    lines += ["", "## Case labs", ""]
    if node["case_labs"]:
        hub_by_id = {hub["id"]: hub for hub in graph["case_labs"]}
        for case_lab in node["case_labs"]:
            hub = hub_by_id[case_lab]
            lines.append(
                f"- {relative_link(page, output / 'case-labs' / f'{case_lab}.md', hub.get('title') or 'Untitled case lab')}"
            )
    else:
        lines.append("No explicitly evidenced case-lab memberships.")
    lines += ["", "## Linked learning artifacts", ""]
    if node["lessons"]:
        for lesson in node["lessons"]:
            lines.append(f"- {source_link(page, root, lesson, Path(lesson).stem)}")
    else:
        lines.append("No linked lessons.")
    if node["records"]:
        for record in node["records"]:
            lines.append(f"- {source_link(page, root, record, Path(record).stem)}")
    else:
        lines.append("No linked learning records.")
    lines += ["", "## Typed local graph", ""] + typed_mermaid(neighbours, graph["edges"])
    lines += [f"Back to {relative_link(page, output / 'README.md', 'Knowledge Map') }.", ""]
    write_page(page, lines)


def render_markdown(root: Path, output: Path, graph: dict[str, Any]) -> None:
    """Render all Markdown views using a prevalidated normalized graph."""

    output.mkdir(parents=True, exist_ok=True)
    render_entrypoint(root, output, graph)
    render_overview(root, output, graph)
    for track in graph["tracks"]:
        render_track(output / "tracks" / f"{track}.md", root, output, graph, track)
    for case_lab in graph["case_labs"]:
        render_case_lab(output / "case-labs" / f"{case_lab['id']}.md", root, output, graph, case_lab)
    for node in graph["nodes"]:
        render_concept(output / "concepts" / f"{node['id']}.md", root, output, graph, node)


def main(arguments: list[str] | None = None) -> int:
    parsed = parse_arguments(sys.argv[1:] if arguments is None else arguments)
    root = parsed.root.resolve()
    output = (parsed.output if parsed.output is not None else root / "maps").resolve()
    try:
        graph = load_graph_builder().validate_knowledge_graph(root)
        render_markdown(root, output, graph)
    except Exception as error:  # The builder's validation errors are user-facing here too.
        print(f"knowledge-map Markdown render failed: {error}", file=sys.stderr)
        return 1
    print(f"knowledge-map Markdown: rendered {len(graph['nodes'])} concepts to {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
